drop table T_USUARIO if exists;
create table T_USUARIO( idUsuario bigint generated by default as identity (start with 1), 
						login varchar(20) not null ,
						password varchar(10) not null, 
						estado char(1) not null,
						nombre varchar(50) not null,
						apellido varchar(100) not null,
						puesto varchar(50) null,
						fec_Creacion varchar(10) not null,
						fec_Caducidad varchar(10) not null,
						telefono varchar(20) not null,
						email varchar(50) not null,
						dni varchar(20) not null,
						tipo char(1) not null,
						unique(login),
						primary key (idUsuario));							

						
drop table T_COMENTARIO if exists;
create table T_COMENTARIO (
	idComentario  bigint generated by default as identity (start with 1);
	idPelicula bigint;
	comentario varchar(500);
	estado varchar(15);			
	fechaRegistro varchar(10);
	primary key (idComentario, idPelicula);
)