drop table T_USUARIO if exists;
create table T_USUARIO( idUsuario bigint generated by default as identity (start with 1), 
						login varchar(20) not null ,
						password varchar(10) not null, 
						estado char(1) not null,
						nombre varchar(50) not null,
						apellido varchar(100) not null,
						puesto varchar(50) null,
						fec_Creacion varchar(10) not null,
						fec_Caducidad varchar(10) not null,
						telefono varchar(20) not null,
						email varchar(50) not null,
						dni varchar(20) not null,
						tipo char(1) not null,
						unique(login),
						primary key (idUsuario));							

drop table T_PELICULA if exists;
create table T_PELICULA( idPelicula bigint generated by default as identity (start with 1), 
						nomPelicula varchar(100) not null ,
						anioProduccion varchar(4) not null, 
						duracion varchar(50) not null,
						paisOrigen varchar(50) not null,
						genero varchar(50) not null,
						tipoEmision varchar(50) null,
						flagSubtitulo char(1) not null,
						flagComentario integer not null,
						publicoObjetivo varchar(100) not null,
						sinopsis varchar(1000) not null,
						fecIniCartelera date not null,
						fecFinCartelera date not null,
						estado varchar(50) not null,
						poster varchar(100) not null,
						trailer varchar(100) not null,
						unique(idPelicula),
						primary key (idPelicula));		
						
						
drop table T_PRODUCTO if exists;
create table T_PRODUCTO( idProducto bigint generated by default as identity (start with 1), 
						nomProducto varchar(100) not null ,
						descProducto varchar(500) not null, 
						precioProducto integer not null,
						stockProducto integer not null,
						caracteristicasProducto varchar(500) not null,
						rutaImagenProducto varchar(100) null,
						estadoProducto varchar(50) not null,
						unique(idProducto),
						primary key (idProducto));		
						

drop table T_MERCHANDIZING if exists;
create table T_MERCHANDIZING( idPelicula integer not null,
						idProducto integer not null,
						fecInicioVigencia date not null,
						fecFinVigencia date not null,
						estadoMerchandizing varchar(50) not null,
						unique(idPelicula, idProducto),
						primary key (idPelicula, idProducto));

drop table T_SUGERENCIA if exists;
create table T_SUGERENCIA( idSugerencia bigint generated by default as identity (start with 1), 
						descripcion varchar(500) not null ,
						estado varchar(50) not null, 
						fecha_registro varchar(10) not null,
						fecha_atencion varchar(10) not null,
						flag_atencion varchar(50) not null,
						unique(idSugerencia),
						primary key (idSugerencia));		


drop table T_COMENTARIO if exists;
create table T_COMENTARIO( 
	idComentario bigint generated by default as identity (start with 1),
	idPelicula bigint not null,
	comentario varchar(500) not null,
	estado varchar(20) not null,
	fechaRegistro char(10) not null,
	unique(idComentario),
	primary key (idComentario));		
